//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "filters")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub name: Option<String>,
    pub enabled: i8,
    pub server: i64,
    pub creator: Option<i64>,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub r#type: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub type_settings: Option<String>,
    pub server_scope: i8,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub server_scope_settings: Option<String>,
    pub user_scope: i8,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub user_scope_settings: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub effect: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
