//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub token: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub session: Option<String>,
    pub task: Option<i32>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub last_known_host: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub last_known_name: Option<String>,
    pub maintainer: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
