//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub enabled: i8,
    pub server: Option<i64>,
    pub creator: Option<i64>,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub target: String,
    pub target_id: i64,
    pub permissions: i64,
    pub unremovable: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
