//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pin_blacklist")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub server: i64,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub channel: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
